karaoke_page_signature = 'שרים קריוקי'
metadata_table_name = 'metadata'
songs_npy_name = 'songs_name'
song_name = 'song.mp3'
karaoke_name = 'karaoke.mp3'
aligned_karaoke_name = 'aligned_karaoke.wav'
aligned_song_name = 'aligned_song.wav'
