methods = ['cv2.TM_CCOEFF', 'cv2.TM_CCOEFF_NORMED', 'cv2.TM_CCORR', 'cv2.TM_CCORR_NORMED', 'cv2.TM_SQDIFF',
           'cv2.TM_SQDIFF_NORMED']
MATCH_TEMPLATE_METHOD = 'cv2.TM_CCORR_NORMED'
PAD_SONG_TIME = 5
KARAOKE_PREFIX_TIME = 8
